export enum RolesUsuario {
    ADMIN = 'ADMIN',
    USER = 'USER',
    OPERADOR_LOGISTICA = 'OPERADOR_LOGISTICA',
    AYUDANTE_MANTENIMIENTO = 'AYUDANTE_MANTENIMIENTO',
    TRIPULACION = 'TRIPULACION'
}
