export enum CargoPersonal {
  MECANICO            = 'MECANICO',
  TECNICO_COMBUSTIBLE = 'TECNICO_COMBUSTIBLE',
  OPERADOR_LOGISTICA  = 'OPERADOR_LOGISTICA',
  INSPECTOR           = 'INSPECTOR',
  SUPERVISOR          = 'SUPERVISOR'
}
